(() => {
  'use strict';
  const URL='https://gconmsfozomwfisnmgdq.supabase.co';
  const KEY='sb_publishable_ZLXQ1aAgucleTv3g6nfOuQ_zB4T6Acd';
  let client=null,user=null,tab='resumen',students=[],packages=[],payments=[],transactions=[];
  const money=v=>'$'+Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Mexico_City'});
  const $=s=>document.querySelector(s);
  function studioMarkup(){return `<section id="phase4-studio" class="p4-wrap" hidden>
    <div class="p4-head"><div><p class="mc-label">DEMETER FITNESS · FASE 4</p><h2>Operación del estudio</h2><p>Alumnas, paquetes, pagos e ingresos del estudio en un solo lugar.</p></div><button class="p4-primary" id="p4-refresh">Actualizar</button></div>
    <nav class="p4-tabs" aria-label="Módulo del estudio">${[['resumen','Resumen'],['alumnas','Alumnas'],['paquetes','Paquetes'],['pagos','Pagos'],['movimientos','Movimientos']].map(([id,label])=>`<button data-p4-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav>
    <div id="p4-content"></div>
    <div id="p4-modal" class="p4-modal" hidden></div>
  </section>`}
  function inject(){if($('.p4-wrap'))return;const main=$('.mc-main');if(!main)return;main.insertAdjacentHTML('beforeend',studioMarkup());const nav=[...document.querySelectorAll('.mc-nav-item')];const est=nav.find(b=>b.dataset.module==='Estudio');if(est){est.disabled=false;est.addEventListener('click',()=>open());}const bottom=[...document.querySelectorAll('.mc-bottom button')];if(bottom[4]){bottom[4].disabled=false;bottom[4].addEventListener('click',()=>open());}$('#p4-refresh').addEventListener('click',load);document.querySelectorAll('[data-p4-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.p4Tab;render()}));}
  function open(){document.querySelectorAll('.mc-main > *').forEach(x=>{if(!x.classList.contains('mc-header')&&!x.classList.contains('mc-scope')&&!x.classList.contains('p4-wrap'))x.hidden=true});$('.p4-wrap').hidden=false;document.querySelector('.mc-scope')?.classList.add('p4-hidden');load();}
  function close(){document.querySelectorAll('.mc-main > *').forEach(x=>x.hidden=false);$('.p4-wrap').hidden=true;document.querySelector('.mc-scope')?.classList.remove('p4-hidden');}
  async function load(){if(!client||!user)return;try{const [s,p,pa,t]=await Promise.all([
    client.from('students').select('*').eq('user_id',user.id).order('name'),
    client.from('packages').select('*').eq('user_id',user.id).order('name'),
    client.from('payments').select('*, students(name), packages:student_packages(package_id, packages(name))').eq('user_id',user.id).order('payment_date',{ascending:false}).limit(100),
    client.from('transactions').select('id,amount,type,concept,transaction_date,account_id,accounts(name)').eq('user_id',user.id).eq('area','studio').order('transaction_date',{ascending:false}).limit(100)
  ]); if(s.error)throw s.error;if(p.error)throw p.error;if(pa.error)throw pa.error;if(t.error)throw t.error;students=s.data||[];packages=p.data||[];payments=pa.data||[];transactions=t.data||[];render();}catch(e){$('#p4-content').innerHTML=`<div class="p4-error">No se pudieron cargar los datos del estudio: ${esc(e.message)}</div>`}}
  function render(){document.querySelectorAll('[data-p4-tab]').forEach(b=>b.classList.toggle('active',b.dataset.p4Tab===tab));const c=$('#p4-content');if(!c)return;({resumen:renderSummary,alumnas:renderStudents,paquetes:renderPackages,pagos:renderPayments,movimientos:renderTransactions}[tab])();}
  function renderSummary(){const active=students.filter(s=>s.status==='active').length;const month=new Date().toLocaleDateString('en-CA',{timeZone:'America/Mexico_City'}).slice(0,7);const income=transactions.filter(t=>t.type==='income'&&String(t.transaction_date).startsWith(month)).reduce((a,t)=>a+Number(t.amount),0);const expense=transactions.filter(t=>t.type==='expense'&&String(t.transaction_date).startsWith(month)).reduce((a,t)=>a+Number(t.amount),0);const pending=students.filter(s=>s.status==='active'&&!payments.some(p=>p.student_id===s.id&&String(p.payment_date).startsWith(month))).length;const expiring=students.filter(s=>s.status==='active').filter(s=>{const p=payments.find(x=>x.student_id===s.id&&x.period_end);return p&&new Date(p.period_end)<new Date(Date.now()+7*86400000)}).length;c=$('#p4-content');c.innerHTML=`<div class="p4-grid"><article class="p4-card"><span>Alumnas activas</span><strong>${active}</strong><small>Estado actual</small></article><article class="p4-card"><span>Ingresos del mes</span><strong>${money(income)}</strong><small>Movimientos reales</small></article><article class="p4-card"><span>Gastos del mes</span><strong>${money(expense)}</strong><small>Área Estudio</small></article><article class="p4-card"><span>Resultado del mes</span><strong>${money(income-expense)}</strong><small>Ingresos − gastos</small></article></div><div class="p4-two"><article class="p4-card"><div class="p4-card-head"><div><span>Atención</span><h3>Seguimiento operativo</h3></div><button class="p4-secondary" data-action="student-new">Nueva alumna</button></div><div class="p4-list"><div><b>${pending}</b><span>alumnas activas sin pago este mes</span></div><div><b>${expiring}</b><span>paquetes con vencimiento cercano</span></div><div><b>${packages.filter(p=>p.active).length}</b><span>paquetes activos</span></div></div></article><article class="p4-card"><div class="p4-card-head"><div><span>Últimos pagos</span><h3>Actividad reciente</h3></div><button class="p4-secondary" data-action="payment-new">Registrar pago</button></div>${payments.slice(0,5).map(p=>`<div class="p4-row"><span><b>${esc(p.students?.name||'Alumna')}</b><small>${esc(p.payment_date)} · ${esc(p.payment_method||'Sin método')}</small></span><strong class="p4-good">${money(p.amount)}</strong></div>`).join('')||'<div class="p4-empty">No hay pagos registrados todavía.</div>'}</article></div>`;bindActions();}
  function renderStudents(){const c=$('#p4-content');c.innerHTML=`<div class="p4-toolbar"><input id="p4-student-search" placeholder="Buscar alumna…"><button class="p4-primary" data-action="student-new">+ Nueva alumna</button></div><div class="p4-table">${students.map(s=>`<div class="p4-row p4-student-row"><span><b>${esc(s.name)}</b><small>${esc(s.phone||'Sin teléfono')} · Ingreso ${esc(s.joined_at||'—')}</small></span><span class="p4-status ${s.status}">${({active:'Activa',paused:'Pausada',inactive:'Inactiva'})[s.status]||s.status}</span><span class="p4-actions"><button data-action="student-edit" data-id="${s.id}">Editar</button><button data-action="student-pay" data-id="${s.id}">Pago</button><button data-action="student-archive" data-id="${s.id}">Archivar</button></span></div>`).join('')||'<div class="p4-empty">No hay alumnas registradas todavía.</div>'}</div>`;bindActions();$('#p4-student-search').addEventListener('input',e=>document.querySelectorAll('.p4-student-row').forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(e.target.value.toLowerCase())));}
  function renderPackages(){const c=$('#p4-content');c.innerHTML=`<div class="p4-toolbar"><div><h3>Paquetes</h3><p>Catálogo privado del estudio.</p></div><button class="p4-primary" data-action="package-new">+ Nuevo paquete</button></div><div class="p4-package-grid">${packages.map(p=>`<article class="p4-card"><div class="p4-card-head"><div><h3>${esc(p.name)}</h3><small>${p.active?'Activo':'Inactivo'}</small></div><strong>${money(p.price)}</strong></div><p>${esc(p.description||'Sin descripción')}</p><div class="p4-package-meta"><span>${p.class_count??'—'} clases</span><span>${p.validity_days??'—'} días</span></div><button class="p4-secondary" data-action="package-edit" data-id="${p.id}">Editar</button></article>`).join('')||'<div class="p4-empty">No hay paquetes registrados.</div>'}</div>`;bindActions();}
  function renderPayments(){const c=$('#p4-content');c.innerHTML=`<div class="p4-toolbar"><div><h3>Pagos</h3><p>Cada pago se refleja como ingreso del estudio.</p></div><button class="p4-primary" data-action="payment-new">+ Registrar pago</button></div><div class="p4-table">${payments.map(p=>`<div class="p4-row"><span><b>${esc(p.students?.name||'Alumna')}</b><small>${esc(p.payment_date)} · ${esc(p.payment_method||'Sin método')}</small></span><strong class="p4-good">${money(p.amount)}</strong><span>${esc(p.period_start||'—')} → ${esc(p.period_end||'—')}</span></div>`).join('')||'<div class="p4-empty">No hay pagos registrados todavía.</div>'}</div>`;bindActions();}
  function renderTransactions(){const c=$('#p4-content');c.innerHTML=`<div class="p4-toolbar"><div><h3>Finanzas del estudio</h3><p>Movimientos reales del área Estudio.</p></div><button class="p4-primary" data-action="transaction-new">+ Nuevo movimiento</button></div><div class="p4-table">${transactions.map(t=>`<div class="p4-row"><span><b>${esc(t.concept||'Movimiento')}</b><small>${esc(t.transaction_date)} · ${esc(t.accounts?.name||'Cuenta')}</small></span><strong class="${t.type==='income'?'p4-good':'p4-bad'}">${t.type==='income'?'+':'−'}${money(t.amount)}</strong></div>`).join('')||'<div class="p4-empty">No hay movimientos del estudio todavía.</div>'}</div>`;bindActions();}
  function bindActions(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions(b.dataset.action,b.dataset.id));}
  async function actions(a,id){if(a==='student-new')return studentForm();if(a==='student-edit')return studentForm(students.find(x=>x.id===id));if(a==='student-pay')return paymentForm(students.find(x=>x.id===id));if(a==='student-archive'){if(confirm('¿Archivar esta alumna?')){await client.from('students').update({status:'inactive'}).eq('id',id).eq('user_id',user.id);await load()}return}if(a==='package-new')return packageForm();if(a==='package-edit')return packageForm(packages.find(x=>x.id===id));if(a==='payment-new')return paymentForm();if(a==='transaction-new')return transactionForm();}
  function modal(title,body){const m=$('#p4-modal');m.hidden=false;m.innerHTML=`<div class="p4-modal-card"><div class="p4-card-head"><h3>${title}</h3><button class="p4-close" data-close>×</button></div>${body}</div>`;m.querySelector('[data-close]').onclick=()=>m.hidden=true;return m.querySelector('form');}
  function studentForm(s={}){const f=modal(s.id?'Editar alumna':'Nueva alumna',`<form id="p4-student-form"><label>Nombre<input name="name" required value="${esc(s.name)}"></label><label>Teléfono<input name="phone" value="${esc(s.phone)}"></label><label>Fecha de ingreso<input name="joined_at" type="date" value="${esc(s.joined_at||today())}"></label><label>Estado<select name="status"><option value="active" ${s.status==='active'?'selected':''}>Activa</option><option value="paused" ${s.status==='paused'?'selected':''}>Pausada</option><option value="inactive" ${s.status==='inactive'?'selected':''}>Inactiva</option></select></label><label>Notas<textarea name="notes">${esc(s.notes)}</textarea></label><button class="p4-primary">Guardar</button></form>`);f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));const q=s.id?client.from('students').update(d).eq('id',s.id).eq('user_id',user.id):client.from('students').insert({...d,user_id:user.id});const r=await q;if(r.error)return alert(r.error.message);f.closest('.p4-modal').hidden=true;await load()};}
  function packageForm(p={}){const f=modal(p.id?'Editar paquete':'Nuevo paquete',`<form><label>Nombre<input name="name" required value="${esc(p.name)}"></label><label>Descripción<input name="description" value="${esc(p.description)}"></label><label>Precio<input name="price" type="number" min="0" step=".01" required value="${p.price??''}"></label><label>Número de clases<input name="class_count" type="number" min="0" value="${p.class_count??''}"></label><label>Vigencia (días)<input name="validity_days" type="number" min="0" value="${p.validity_days??''}"></label><label>Estado<select name="active"><option value="true" ${p.active!==false?'selected':''}>Activo</option><option value="false" ${p.active===false?'selected':''}>Inactivo</option></select></label><button class="p4-primary">Guardar</button></form>`);f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));d.price=Number(d.price);d.class_count=d.class_count?Number(d.class_count):null;d.validity_days=d.validity_days?Number(d.validity_days):null;d.active=d.active==='true';const r=p.id?await client.from('packages').update(d).eq('id',p.id).eq('user_id',user.id):await client.from('packages').insert({...d,user_id:user.id});if(r.error)return alert(r.error.message);f.closest('.p4-modal').hidden=true;await load()};}
  function paymentForm(pre){const f=modal('Registrar pago',`<form><label>Alumna<select name="student_id" required><option value="">Selecciona</option>${students.map(s=>`<option value="${s.id}" ${pre?.id===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Paquete<select name="package_id"><option value="">Sin paquete</option>${packages.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.price)}</option>`).join('')}</select></label><label>Monto<input name="amount" type="number" min="0" step=".01" required></label><label>Fecha<input name="payment_date" type="date" value="${today()}" required></label><label>Método<select name="payment_method"><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select></label><label>Periodo inicio<input name="period_start" type="date"></label><label>Periodo fin<input name="period_end" type="date"></label><label>Nota<textarea name="note"></textarea></label><button class="p4-primary">Registrar pago</button></form>`);f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));d.amount=Number(d.amount);const student=students.find(s=>s.id===d.student_id);if(!student)return;const pkg=packages.find(p=>p.id===d.package_id);const start=d.period_start||d.payment_date;let expiration=d.period_end||null;if(!expiration&&pkg?.validity_days)expiration=new Date(new Date(start+'T12:00:00').getTime()+pkg.validity_days*86400000).toISOString().slice(0,10);let sp=null;if(pkg){const sr=await client.from('student_packages').insert({user_id:user.id,student_id:student.id,package_id:pkg.id,price:d.amount,start_date:start,expiration_date:expiration,status:'active'}).select('id').single();if(sr.error)return alert(sr.error.message);sp=sr.data.id;}const pr=await client.from('payments').insert({user_id:user.id,student_id:student.id,student_package_id:sp,amount:d.amount,payment_date:d.payment_date,payment_method:d.payment_method,period_start:start,period_end:expiration,note:d.note});if(pr.error)return alert(pr.error.message);f.closest('.p4-modal').hidden=true;await load()};}
  function transactionForm(){const f=modal('Nuevo movimiento del estudio',`<form><label>Tipo<select name="type"><option value="expense">Gasto</option><option value="income">Ingreso</option></select></label><label>Monto<input name="amount" type="number" min="0" step=".01" required></label><label>Cuenta<select name="account_id" required><option value="">Cargando cuentas…</option></select></label><label>Concepto<input name="concept" required></label><label>Fecha<input name="transaction_date" type="date" value="${today()}" required></label><button class="p4-primary">Guardar</button></form>`);client.from('accounts').select('id,name').eq('user_id',user.id).eq('area','studio').eq('type','asset').order('name').then(r=>{if(!r.error)f.account_id.innerHTML=r.data.length?r.data.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''):'<option value="">Crea una cuenta de activo del estudio primero</option>'});f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));d.amount=Number(d.amount);const r=await client.from('transactions').insert({...d,user_id:user.id,area:'studio'});if(r.error)return alert(r.error.message);f.closest('.p4-modal').hidden=true;await load()};}
  function start(){client=window.supabase.createClient(URL,KEY);const wait=setInterval(async()=>{const shell=document.querySelector('.mc-app');if(!shell)return;if(!$('.p4-wrap'))inject();const s=await client.auth.getSession();if(s.data.session){user=s.data.session.user;clearInterval(wait);await load();}},500);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();