(()=>{
const KEY='demeter_custom_goals_v1';
const $=id=>document.getElementById(id);
const money=v=>'$'+Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let goals=[];try{goals=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{goals=[]}
function save(){localStorage.setItem(KEY,JSON.stringify(goals))}
let initialized=false;
function inject(){
 const host=$('goalsPage');
 if(!host||$('customGoalsMount'))return;
 if(!initialized){
  initialized=true;
  const css=document.createElement('style');css.textContent='.custom-goals{margin-top:14px;padding-top:14px;border-top:1px solid #292d32}.custom-title{display:flex;justify-content:space-between;align-items:center;gap:10px}.custom-add{border:1px solid #ff2f79;background:#351622;color:#ff78aa;border-radius:12px;padding:9px 12px;font-weight:850}.custom-card{background:#15181c;border:1px solid #2b3035;border-radius:17px;padding:14px;margin-top:9px}.custom-actions{display:flex;gap:7px;margin-top:10px}.custom-actions button{flex:1}.custom-empty{color:#92979b;font-size:12px;padding:10px 0}.goal-modal{position:fixed;inset:0;background:rgba(0,0,0,.78);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;z-index:40;padding:12px}.goal-modal-card{width:min(520px,100%);background:#16191c;border:1px solid #2b3035;border-radius:24px;padding:20px}.goal-modal-head{display:flex;justify-content:space-between;align-items:center}.goal-modal-head h2{margin:0}.goal-close{border:0;background:#25292d;color:#fff;border-radius:50%;width:34px;height:34px;font-size:18px}.goal-modal form{display:grid;gap:9px;margin-top:12px}.goal-modal label{font-size:12px;color:#92979b;font-weight:750}.goal-modal input,.goal-modal select{width:100%;box-sizing:border-box;border:1px solid #30353a;border-radius:14px;padding:12px;background:#1a1d21;color:#f7f7f5}.goal-modal .primary{border:0;background:linear-gradient(135deg,#ff2f79,#ff4d8d);color:#fff;border-radius:14px;padding:13px;font-weight:900}@media(min-width:720px){.goal-modal{align-items:center}.goal-modal-card{border-radius:24px}}';document.head.appendChild(css);
  const modal=document.createElement('div');modal.id='customGoalModal';modal.className='goal-modal hidden';modal.innerHTML='<div class="goal-modal-card"><div class="goal-modal-head"><h2 id="customGoalHeading">Nueva meta</h2><button type="button" class="goal-close" id="customGoalClose">×</button></div><form id="customGoalForm"><input id="customGoalId" type="hidden"><label>Nombre<input id="customGoalName" maxlength="60" placeholder="Ej. Viaje a Japón" required></label><label>Objetivo<input id="customGoalTarget" type="number" min="1" step=".01" placeholder="0.00" required></label><label>Capital actual<input id="customGoalCurrent" type="number" min="0" step=".01" value="0"></label><label>Fecha objetivo<input id="customGoalDate" type="date"></label><label>Prioridad<select id="customGoalPriority"><option value="media">Media</option><option value="alta">Alta</option><option value="baja">Baja</option></select></label><button type="submit" class="primary">Guardar meta</button></form></div>';document.body.appendChild(modal);
  $('customGoalClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};$('customGoalForm').onsubmit=e=>{e.preventDefault();const name=$('customGoalName').value.trim(),target=Number($('customGoalTarget').value);if(!name||!Number.isFinite(target)||target<=0)return;const id=$('customGoalId').value||((window.crypto&&crypto.randomUUID)?crypto.randomUUID():String(Date.now()));const g={id,name,target,current:Math.min(target,Math.max(0,Number($('customGoalCurrent').value||0))),date:$('customGoalDate').value,priority:$('customGoalPriority').value};const i=goals.findIndex(x=>x.id===id);if(i>=0)goals[i]=g;else goals.push(g);save();close();render()};
 }
 const wrap=document.createElement('div');wrap.id='customGoalsMount';wrap.className='custom-goals';wrap.innerHTML='<div class="custom-title"><div><div class="kicker">🎯 Metas personalizadas</div><div class="note">Crea objetivos adicionales sin alterar las metas base.</div></div><button type="button" class="custom-add" id="addCustomGoal">＋ Nueva meta</button></div><div id="customGoalList"></div>';host.appendChild(wrap);
 $('addCustomGoal').onclick=()=>open();render();
}
function open(id){const g=goals.find(x=>x.id===id);$('customGoalHeading').textContent=g?'Editar meta':'Nueva meta';$('customGoalId').value=g?.id||'';$('customGoalName').value=g?.name||'';$('customGoalTarget').value=g?.target||'';$('customGoalCurrent').value=g?.current??0;$('customGoalDate').value=g?.date||'';$('customGoalPriority').value=g?.priority||'media';$('customGoalModal').classList.remove('hidden');setTimeout(()=>$('customGoalName').focus(),0)}
function close(){$('customGoalModal').classList.add('hidden')}
function render(){const e=$('customGoalList');if(!e)return;if(!goals.length){e.innerHTML='<div class="custom-empty">Todavía no tienes metas personalizadas.</div>';return}e.innerHTML=goals.map(g=>{const pct=Math.min(100,g.target?g.current/g.target*100:0),p=g.priority==='alta'?'Alta':g.priority==='baja'?'Baja':'Media';return `<div class="custom-card"><div class="goal-top"><div class="goal-title">${esc(g.name)}</div><div class="goal-priority ${g.priority==='alta'?'high':g.priority==='baja'?'low':''}">${p}</div></div><div class="goal-value">${money(g.current)}</div><div class="muted">Objetivo: ${money(g.target)}${g.date?' · '+esc(g.date):''}</div><div class="progress" style="margin-top:10px"><div class="fill ${g.priority==='baja'?'green':''}" style="width:${pct}%"></div></div><div class="goal-grid" style="margin-top:10px"><div class="goal-kpi"><span>Progreso</span><b>${pct.toFixed(1)}%</b></div><div class="goal-kpi"><span>Faltante</span><b>${money(Math.max(0,g.target-g.current))}</b></div></div><div class="custom-actions"><button type="button" class="secondary" data-edit="${esc(g.id)}">Editar</button><button type="button" class="icon-btn delete" data-delete="${esc(g.id)}">Eliminar</button></div></div>`}).join('');e.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(b.dataset.edit));e.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar esta meta personalizada?')){goals=goals.filter(x=>x.id!==b.dataset.delete);save();render()}})}
}
function watch(){const host=$('goalsPage');if(!host)return;new MutationObserver(()=>{if(!$('customGoalsMount'))inject()}).observe(host,{childList:true});inject()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();