(()=>{
  'use strict';
  function installVisualLayer(){
    if(document.getElementById('mc-safe-visual-layer'))return;
    document.documentElement.classList.add('phase1');
    document.body.classList.add('mc-page');
    const style=document.createElement('style');style.id='mc-safe-visual-layer';style.textContent=`
      :root{--mc-bg:#FBF9F7;--mc-ink:#273247;--mc-muted:#777986;--mc-pink:#E9B9BA;--mc-pink-soft:#F8E7E6;--mc-mint:#9FC8B0;--mc-mint-soft:#E2F0E8;--mc-sky:#A9C7E5;--mc-sky-soft:#E4EEF8;--mc-peach:#E5B884;--mc-peach-soft:#F9E9D7;--mc-border:#E6E1DE;--mc-shadow:0 8px 28px rgba(53,58,72,.07)}
      html.phase1,html.phase1 body{background:var(--mc-bg)!important;color:var(--mc-ink)!important}body.mc-page{min-height:100vh;font-family:Inter,system-ui,-apple-system,sans-serif!important;color:var(--mc-ink)!important}
      body.mc-page .top{background:rgba(255,255,255,.94)!important;color:var(--mc-ink)!important;border-bottom:1px solid var(--mc-border)!important;box-shadow:0 3px 18px rgba(53,58,72,.04)!important}body.mc-page .brand{color:var(--mc-muted)!important}.mc-page .date{background:var(--mc-pink-soft)!important;color:#9B6567!important;border-color:transparent!important}.mc-page h1{color:var(--mc-ink)!important;font-family:Manrope,Inter,sans-serif!important}.mc-page .sub,.mc-page .muted,.mc-page .note{color:var(--mc-muted)!important}
      body.mc-page main{max-width:1400px!important;padding:28px clamp(16px,4vw,58px) 100px!important}.mc-page .segment{background:#EEECEA!important;border-color:transparent!important;box-shadow:none!important}.mc-page .segment button{color:var(--mc-muted)!important}.mc-page .segment button.active{background:#fff!important;color:#C96F72!important;box-shadow:0 4px 14px rgba(53,58,72,.08)!important}.mc-page .card{background:#fff!important;color:var(--mc-ink)!important;border:1px solid var(--mc-border)!important;box-shadow:var(--mc-shadow)!important;border-radius:20px!important}
      .mc-page .metric{background:#fff!important;color:var(--mc-ink)!important}.mc-page .metric-g{border-left:4px solid var(--mc-mint)!important;background:linear-gradient(145deg,#fff,#F3F8F5)!important}.mc-page .metric-p{border-left:4px solid var(--mc-pink)!important;background:linear-gradient(145deg,#fff,#FCF2F1)!important}.mc-page .metric-o{border-left:4px solid var(--mc-peach)!important;background:linear-gradient(145deg,#fff,#FCF5ED)!important}.mc-page .metric-b{border-left:4px solid var(--mc-sky)!important;background:linear-gradient(145deg,#fff,#F2F7FC)!important}.mc-page .big{color:var(--mc-ink)!important}.mc-page .good{color:#67977A!important}.mc-page .bad{color:#B86E70!important}.mc-page .blue{color:#607B9D!important}.mc-page .kicker{color:#817E87!important}.mc-page .mini,.mc-page .analytics-card,.mc-page .goal-kpi,.mc-page .goal-next{background:#FBF9F7!important;border-color:var(--mc-border)!important;color:var(--mc-ink)!important}.mc-page .goal-card{background:#fff!important;border-color:var(--mc-border)!important}.mc-page .progress{background:#ECE9E6!important}.mc-page .fill{background:#E9B9BA!important}.mc-page .fill.green{background:#9FC8B0!important}.mc-page .primary{background:#D98285!important;box-shadow:0 6px 16px rgba(217,130,133,.16)!important}.mc-page .secondary,.mc-page input,.mc-page select{background:#FCFBFA!important;color:var(--mc-ink)!important;border-color:#DDD8D4!important}.mc-page input:focus,.mc-page select:focus{border-color:#E9B9BA!important;box-shadow:0 0 0 3px rgba(233,185,186,.18)!important}.mc-page .quick button{background:#fff!important;color:#5E6675!important;border-color:var(--mc-border)!important;box-shadow:var(--mc-shadow)!important}.mc-page .error{background:#FBEFEF!important;color:#8E4545!important;border-color:#E5CACA!important}.mc-page .alert{background:#FCF5ED!important;border-color:#EADFCC!important}.mc-page .modal-card{background:#fff!important;color:var(--mc-ink)!important;border-color:var(--mc-border)!important}.mc-page .goal-priority.high{background:var(--mc-pink-soft)!important;color:#A85E61!important}.mc-page .goal-priority.low{background:var(--mc-mint-soft)!important;color:#5D866B!important}
      .mc-safe-sidebar{position:fixed;inset:0 auto 0 0;width:236px;padding:24px 14px;background:#fff;border-right:1px solid var(--mc-border);z-index:15;display:flex;flex-direction:column;gap:16px}.mc-safe-brand{display:flex;align-items:center;gap:10px;padding:4px 8px 12px;font-family:Manrope,Inter,sans-serif}.mc-safe-mark{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;background:var(--mc-pink-soft);color:#C96F72;font-weight:800;border:1px solid #F0D4D3}.mc-safe-brand strong{display:block;font-size:14px;color:var(--mc-ink)}.mc-safe-brand small{color:var(--mc-muted);font-size:10px}.mc-safe-nav{display:grid;gap:5px}.mc-safe-nav button{border:0;background:transparent;color:#657084;border-radius:13px;padding:11px 12px;text-align:left;font-weight:700;font-size:12px;transition:.18s}.mc-safe-nav button.active{background:var(--mc-pink-soft);color:#C96F72}.mc-safe-nav button:nth-child(2):hover{background:var(--mc-mint-soft)}.mc-safe-nav button:nth-child(3):hover{background:var(--mc-sky-soft)}.mc-safe-nav button:nth-child(4):hover{background:var(--mc-peach-soft)}.mc-safe-foot{margin-top:auto;color:#99939a;font-size:9px;padding:8px;display:flex;justify-content:space-between}body.mc-page .top,body.mc-page main{margin-left:236px}body.mc-page .top{padding-left:clamp(20px,4vw,58px)!important;padding-right:clamp(20px,4vw,58px)!important}
      @media(max-width:700px){.mc-safe-sidebar{display:none}body.mc-page .top,body.mc-page main{margin-left:0}body.mc-page .top{padding:18px 15px!important}body.mc-page main{padding:18px 15px 92px!important}.mc-safe-bottom{position:fixed;display:flex;left:0;right:0;bottom:0;height:68px;background:rgba(255,255,255,.96);backdrop-filter:blur(15px);border-top:1px solid var(--mc-border);z-index:20;padding-bottom:env(safe-area-inset-bottom)}.mc-safe-bottom button{flex:1;border:0;background:transparent;color:#858A95;font-size:9px;font-weight:700}.mc-safe-bottom button span{display:block;font-size:18px;margin:7px 0 2px}.mc-safe-bottom button.active{color:#C96F72}.mc-page .grid{gap:12px}.mc-page .metric{border-radius:18px!important}}
    `;document.head.appendChild(style);
    const sidebar=document.createElement('aside');sidebar.className='mc-safe-sidebar';sidebar.setAttribute('aria-label','Navegación principal');sidebar.innerHTML='<div class="mc-safe-brand"><span class="mc-safe-mark">M</span><div><strong>Mi Centro</strong><small>de Control</small></div></div><nav class="mc-safe-nav"><button data-view="dashboard" class="active">⌂ &nbsp; Inicio</button><button data-view="registrar">$ &nbsp; Finanzas</button><button data-view="finanzas">▤ &nbsp; Presupuestos</button><button data-view="metas">◇ &nbsp; Metas</button></nav><div class="mc-safe-foot"><span>MXN</span><span>CDMX</span></div>';
    const bottom=document.createElement('nav');bottom.className='mc-safe-bottom';bottom.setAttribute('aria-label','Navegación móvil');bottom.innerHTML='<button data-view="dashboard" class="active"><span>⌂</span>Inicio</button><button data-view="registrar"><span>$</span>Finanzas</button><button data-view="finanzas"><span>▤</span>Presupuestos</button><button data-view="metas"><span>◇</span>Metas</button>';
    document.body.prepend(sidebar);document.body.appendChild(bottom);
    function navigate(view){document.querySelectorAll('.mc-safe-nav button,.mc-safe-bottom button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('[data-view="'+view+'"]').forEach(b=>b.classList.add('active'));try{if(typeof window.show==='function')window.show(view,document.querySelector('#tabs button'))}catch(e){console.warn('Navigation bridge:',e)}}
    document.querySelectorAll('.mc-safe-nav button,.mc-safe-bottom button').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
    const syncAuth=()=>{try{const app=document.getElementById('appView'),login=document.getElementById('loginView');if(typeof currentUser!=='undefined'&&currentUser){app?.classList.remove('hidden');document.getElementById('tabs')?.classList.remove('hidden');login?.classList.add('hidden')}else if(app?.classList.contains('hidden'))login?.classList.remove('hidden')}catch(e){}};setInterval(syncAuth,500);syncAuth();
    const p6css=document.createElement('link');p6css.rel='stylesheet';p6css.href='phase6-wellbeing.css';document.head.appendChild(p6css);const p6script=document.createElement('script');p6script.src='phase6-wellbeing.js';p6script.defer=true;document.body.appendChild(p6script);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installVisualLayer,{once:true});else installVisualLayer();
})();