(() => {
  'use strict';
  function installVisualLayer() {
    if (document.getElementById('mc-safe-visual-layer')) return;
    document.documentElement.classList.add('phase1');
    document.body.classList.add('mc-page');
    const style = document.createElement('style');
    style.id = 'mc-safe-visual-layer';
    style.textContent = `
      :root{--mc-bg:#F8F7F4;--mc-ink:#25242A;--mc-primary:#56345C;--mc-secondary:#A982B5;--mc-success:#7AA68A;--mc-warning:#D99A3D;--mc-danger:#C85C5C;--mc-line:#dedbd5}
      html.phase1,html.phase1 body{background:var(--mc-bg)!important;color:var(--mc-ink)!important}body.mc-page{min-height:100vh;font-family:Inter,system-ui,-apple-system,sans-serif!important}
      body.mc-page .top{background:#fff!important;color:var(--mc-ink)!important;border-bottom:1px solid var(--mc-line)!important;box-shadow:0 4px 20px rgba(37,36,42,.04)!important}
      body.mc-page .brand{color:#817a84!important}body.mc-page .date{background:#f1efec!important;color:#6f6971!important;border-color:var(--mc-line)!important}body.mc-page h1{color:var(--mc-ink)!important;font-family:Manrope,Inter,sans-serif!important}body.mc-page .sub{color:#777178!important}
      body.mc-page main{max-width:1400px!important;padding:28px clamp(16px,4vw,58px) 100px!important}body.mc-page .segment{background:#e8e5df!important;border-color:transparent!important;box-shadow:none!important}body.mc-page .segment button{color:#726c73!important}body.mc-page .segment button.active{background:#fff!important;color:var(--mc-primary)!important;box-shadow:0 3px 12px rgba(37,36,42,.08)!important}
      body.mc-page .card{background:#fff!important;color:var(--mc-ink)!important;border:1px solid var(--mc-line)!important;box-shadow:0 8px 30px rgba(37,36,42,.06)!important;border-radius:18px!important}body.mc-page .metric{background:#fff!important;color:var(--mc-ink)!important}.metric-g{border-left:4px solid var(--mc-success)!important}.metric-p{border-left:4px solid var(--mc-primary)!important}.metric-o{border-left:4px solid var(--mc-warning)!important}.metric-b{border-left:4px solid #8C93AD!important}.mc-page .big{color:var(--mc-ink)!important}.mc-page .good{color:var(--mc-success)!important}.mc-page .bad{color:var(--mc-danger)!important}.mc-page .blue{color:#68738F!important}.mc-page .kicker{color:#817A84!important}.mc-page .muted,.mc-page .note{color:#777178!important}
      body.mc-page .mini,body.mc-page .analytics-card,body.mc-page .goal-kpi,body.mc-page .goal-next{background:#F8F7F4!important;border-color:var(--mc-line)!important;color:var(--mc-ink)!important}body.mc-page .goal-card{background:#fff!important;border-color:var(--mc-line)!important}body.mc-page .progress{background:#e8e5df!important}body.mc-page .fill{background:var(--mc-primary)!important}body.mc-page .fill.green{background:var(--mc-success)!important}body.mc-page .primary{background:var(--mc-primary)!important;box-shadow:none!important}body.mc-page .secondary,body.mc-page input,body.mc-page select{background:#FAF9F7!important;color:var(--mc-ink)!important;border-color:#d8d4cf!important}body.mc-page .quick button{background:#fff!important;color:#5f5961!important;border-color:var(--mc-line)!important;box-shadow:0 8px 30px rgba(37,36,42,.06)!important}body.mc-page .error{background:#FBEFEF!important;color:#8E4545!important;border-color:#E5CACA!important}body.mc-page .alert{background:#FBF5EC!important;border-color:#EADFCC!important}body.mc-page .modal-card{background:#fff!important;color:var(--mc-ink)!important;border-color:var(--mc-line)!important}
      .mc-safe-sidebar{position:fixed;inset:0 auto 0 0;width:236px;padding:24px 14px;background:#fff;border-right:1px solid var(--mc-line);z-index:15;display:flex;flex-direction:column;gap:16px}.mc-safe-brand{display:flex;align-items:center;gap:10px;padding:4px 8px 12px;font-family:Manrope,Inter,sans-serif}.mc-safe-mark{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:var(--mc-primary);color:#fff;font-weight:800}.mc-safe-brand strong{display:block;font-size:14px;color:var(--mc-ink)}.mc-safe-brand small{color:#817a84;font-size:10px}.mc-safe-nav{display:grid;gap:4px}.mc-safe-nav button{border:0;background:transparent;color:#6f6a71;border-radius:11px;padding:10px 11px;text-align:left;font-weight:700;font-size:12px}.mc-safe-nav button.active{background:#f0e9f1;color:var(--mc-primary)}.mc-safe-foot{margin-top:auto;color:#99939a;font-size:9px;padding:8px;display:flex;justify-content:space-between}.mc-safe-bottom{display:none}body.mc-page .top,body.mc-page main{margin-left:236px}body.mc-page .top{padding-left:clamp(20px,4vw,58px)!important;padding-right:clamp(20px,4vw,58px)!important}
      @media(max-width:700px){.mc-safe-sidebar{display:none}body.mc-page .top,body.mc-page main{margin-left:0}body.mc-page .top{padding:18px 15px!important}body.mc-page main{padding:18px 15px 90px!important}.mc-safe-bottom{position:fixed;display:flex;left:0;right:0;bottom:0;height:68px;background:rgba(255,255,255,.96);backdrop-filter:blur(15px);border-top:1px solid var(--mc-line);z-index:20;padding-bottom:env(safe-area-inset-bottom)}.mc-safe-bottom button{flex:1;border:0;background:transparent;color:#88828a;font-size:9px;font-weight:700}.mc-safe-bottom button span{display:block;font-size:18px;margin:7px 0 2px}.mc-safe-bottom button.active{color:var(--mc-primary)}}`;
    document.head.appendChild(style);
    const sidebar=document.createElement('aside');sidebar.className='mc-safe-sidebar';sidebar.setAttribute('aria-label','Navegación principal');sidebar.innerHTML='<div class="mc-safe-brand"><span class="mc-safe-mark">M</span><div><strong>Mi Centro</strong><small>de Control</small></div></div><nav class="mc-safe-nav"><button data-view="dashboard" class="active">⌂ &nbsp; Inicio</button><button data-view="registrar">$ &nbsp; Finanzas</button><button data-view="finanzas">▤ &nbsp; Presupuestos</button><button data-view="metas">◇ &nbsp; Metas</button></nav><div class="mc-safe-foot"><span>MXN</span><span>CDMX</span></div>';
    const bottom=document.createElement('nav');bottom.className='mc-safe-bottom';bottom.setAttribute('aria-label','Navegación móvil');bottom.innerHTML='<button data-view="dashboard" class="active"><span>⌂</span>Inicio</button><button data-view="registrar"><span>$</span>Finanzas</button><button data-view="finanzas"><span>▤</span>Presupuestos</button><button data-view="metas"><span>◇</span>Metas</button>';
    document.body.prepend(sidebar);document.body.appendChild(bottom);
    function navigate(view){document.querySelectorAll('.mc-safe-nav button,.mc-safe-bottom button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('[data-view="'+view+'"]').forEach(b=>b.classList.add('active'));if(typeof window.show==='function')window.show(view);}
    document.querySelectorAll('.mc-safe-nav button,.mc-safe-bottom button').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installVisualLayer,{once:true});else installVisualLayer();
})();