(()=>{
  'use strict';
  const css=`
:root{--ui-bg:#fbfaf8;--ui-ink:#20304a;--ui-muted:#737987;--ui-border:#e9e5e1;--ui-pink:#f6dfe1;--ui-pink-strong:#d96f82;--ui-mint:#e4f1e9;--ui-mint-strong:#72aa8b;--ui-sky:#e6eef8;--ui-sky-strong:#6d9fd2;--ui-peach:#faead9;--ui-peach-strong:#e39a4e;--ui-shadow:0 6px 22px rgba(32,48,74,.055)}
html.phase1,html.phase1 body{background:var(--ui-bg)!important;color:var(--ui-ink)!important}body.mc-page{font-family:Inter,system-ui,-apple-system,sans-serif!important;background:var(--ui-bg)!important}.mc-page .top{background:rgba(255,255,255,.96)!important;color:var(--ui-ink)!important;border-bottom:1px solid var(--ui-border)!important;box-shadow:0 2px 14px rgba(32,48,74,.035)!important}.mc-page .brand{color:#778090!important}.mc-page .date{background:#f5f2ef!important;color:#667080!important;border-color:transparent!important}.mc-page h1{color:var(--ui-ink)!important;font-family:Manrope,Inter,sans-serif!important}.mc-page .sub,.mc-page .muted,.mc-page .note{color:var(--ui-muted)!important}
.mc-page main{max-width:1400px!important;padding:24px clamp(16px,4vw,52px) 96px!important}.mc-page .segment{background:#eeeae7!important;border:0!important;box-shadow:none!important;border-radius:16px!important}.mc-page .segment button{color:#737987!important}.mc-page .segment button.active{background:#fff!important;color:var(--ui-pink-strong)!important;box-shadow:0 3px 12px rgba(32,48,74,.07)!important}.mc-page .card{background:#fff!important;color:var(--ui-ink)!important;border:1px solid var(--ui-border)!important;box-shadow:var(--ui-shadow)!important;border-radius:20px!important}.mc-page input,.mc-page select,.mc-page .secondary{background:#fff!important;color:var(--ui-ink)!important;border-color:#ddd8d4!important}.mc-page .primary{background:var(--ui-pink-strong)!important;box-shadow:none!important}.mc-page .error{background:#fff0f0!important;color:#9b4d57!important;border-color:#ebcccc!important}.mc-page .modal-card{background:#fff!important;color:var(--ui-ink)!important;border-color:var(--ui-border)!important}
.mc-page .mc-old-dashboard{display:none!important}.mc-page .mc-home-redesign{display:grid!important}
.mc-home-redesign{grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.mc-home-redesign .home-welcome{grid-column:1/-1;display:flex;align-items:flex-end;justify-content:space-between;padding:8px 2px 5px}.mc-home-redesign .home-welcome h2{font:800 clamp(27px,3vw,39px)/1.05 Manrope;margin:4px 0 6px;letter-spacing:-.04em}.mc-home-redesign .home-welcome p{margin:0;color:var(--ui-muted);font-size:14px}.mc-home-redesign .home-action{border:1px solid var(--ui-border);background:#fff;color:var(--ui-ink);border-radius:13px;padding:11px 15px;font-weight:750}.mc-home-redesign .home-kpi{min-height:132px;padding:17px;position:relative;overflow:hidden}.mc-home-redesign .home-kpi:after{content:"";position:absolute;width:92px;height:92px;border-radius:50%;right:-34px;top:-35px;background:currentColor;opacity:.11}.home-kpi .home-icon{font-size:25px;margin-bottom:16px}.home-kpi .home-label{font-size:12px;color:var(--ui-muted);font-weight:700}.home-kpi .home-value{font:800 25px Manrope;margin-top:4px;letter-spacing:-.035em}.home-pink{background:linear-gradient(145deg,#fff,var(--ui-pink))!important;color:var(--ui-pink-strong)}.home-mint{background:linear-gradient(145deg,#fff,var(--ui-mint))!important;color:var(--ui-mint-strong)}.home-sky{background:linear-gradient(145deg,#fff,var(--ui-sky))!important;color:var(--ui-sky-strong)}.home-peach{background:linear-gradient(145deg,#fff,var(--ui-peach))!important;color:var(--ui-peach-strong)}
.mc-home-redesign .home-panel{padding:19px}.home-panel-wide{grid-column:span 3}.home-panel-side{grid-column:span 1}.home-panel h3{font:750 17px Manrope;margin:0 0 13px}.home-list{display:grid;gap:8px}.home-list-item{display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:13px;background:#fcfbfa;border:1px solid #eeeae6}.home-dot{width:9px;height:9px;border-radius:50%;background:var(--ui-pink-strong);flex:0 0 auto}.home-empty{padding:15px 0;color:var(--ui-muted);font-size:12px}.home-link{border:0;background:none;color:var(--ui-pink-strong);font-weight:750;padding:0;font-size:12px}.home-modules{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.home-module{min-height:112px;padding:17px;display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.home-module h4{font:750 15px Manrope;margin:0 0 6px}.home-module p{margin:0;color:var(--ui-muted);font-size:11px;line-height:1.45}.home-module .module-icon{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;font-size:20px;flex:0 0 auto}.home-module-pink{background:#fff7f7!important}.home-module-pink .module-icon{background:var(--ui-pink);color:var(--ui-pink-strong)}.home-module-mint{background:#f7fbf8!important}.home-module-mint .module-icon{background:var(--ui-mint);color:var(--ui-mint-strong)}.home-module-sky{background:#f7faff!important}.home-module-sky .module-icon{background:var(--ui-sky);color:var(--ui-sky-strong)}.home-module-peach{background:#fffbf6!important}.home-module-peach .module-icon{background:var(--ui-peach);color:var(--ui-peach-strong)}
.mc-safe-sidebar{position:fixed;inset:0 auto 0 0;width:228px;padding:22px 13px;background:#fff;border-right:1px solid var(--ui-border);z-index:15;display:flex;flex-direction:column;gap:18px}.mc-safe-brand{display:flex;align-items:center;gap:10px;padding:4px 9px 10px;font-family:Manrope}.mc-safe-mark{width:35px;height:35px;border-radius:11px;display:grid;place-items:center;background:var(--ui-pink);color:var(--ui-pink-strong);font-weight:900}.mc-safe-brand strong{display:block;font-size:14px}.mc-safe-brand small{display:block;color:var(--ui-muted);font-size:10px}.mc-safe-nav{display:grid;gap:3px}.mc-safe-nav button{border:0;background:transparent;color:#6d7481;border-radius:12px;padding:11px 12px;text-align:left;font-weight:700;font-size:12px}.mc-safe-nav button.active{background:#fff0f1;color:var(--ui-pink-strong)}.mc-safe-foot{margin-top:auto;color:#9a9fa8;font-size:9px;padding:8px;display:flex;justify-content:space-between}.mc-safe-bottom{display:none}body.mc-page .top,body.mc-page main{margin-left:228px}body.mc-page .top{padding-left:clamp(18px,4vw,52px)!important;padding-right:clamp(18px,4vw,52px)!important}
.mc-page .top>*,.mc-page main>*{max-width:100%}
@media(max-width:850px){.home-panel-wide,.home-panel-side{grid-column:1/-1}.home-modules{grid-template-columns:repeat(2,minmax(0,1fr))}.mc-home-redesign{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:700px){.mc-safe-sidebar{display:none}body.mc-page .top,body.mc-page main{margin-left:0}body.mc-page .top{padding:17px 15px!important}body.mc-page main{padding:17px 15px 88px!important}.mc-safe-bottom{position:fixed;display:flex;left:0;right:0;bottom:0;height:68px;background:rgba(255,255,255,.97);backdrop-filter:blur(15px);border-top:1px solid var(--ui-border);z-index:20;padding-bottom:env(safe-area-inset-bottom)}.mc-safe-bottom button{flex:1;border:0;background:transparent;color:#858b96;font-size:9px;font-weight:750}.mc-safe-bottom button span{display:block;font-size:18px;margin:7px 0 2px}.mc-safe-bottom button.active{color:var(--ui-pink-strong)}.mc-home-redesign{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.mc-home-redesign .home-welcome{grid-column:1/-1;display:block}.mc-home-redesign .home-welcome h2{font-size:28px}.mc-home-redesign .home-action{display:none}.mc-home-redesign .home-kpi{min-height:116px;padding:14px}.home-kpi .home-icon{font-size:21px;margin-bottom:11px}.home-kpi .home-value{font-size:21px}.home-panel-wide,.home-panel-side{grid-column:1/-1}.home-modules{grid-template-columns:1fr 1fr;gap:10px}.home-module{min-height:105px;padding:14px}.home-module h4{font-size:14px}.home-module p{font-size:10px}.mc-page .segment{margin-bottom:12px}}
@media(max-width:390px){.home-modules{grid-template-columns:1fr}.mc-home-redesign .home-kpi{min-height:110px}}
`;
  function addStyle(){if(document.getElementById('mc-intuitive-style'))return;const s=document.createElement('style');s.id='mc-intuitive-style';s.textContent=css;document.head.appendChild(s)}
  function buildHome(){
    const dash=document.getElementById('dashboard'); if(!dash||document.getElementById('mc-home-redesign'))return;
    const old=document.createElement('div');old.className='mc-old-dashboard';while(dash.firstChild)old.appendChild(dash.firstChild);dash.appendChild(old);
    const home=document.createElement('div');home.id='mc-home-redesign';home.className='mc-home-redesign';
    home.innerHTML=`
      <div class="home-welcome"><div><p class="home-label">CENTRO DE CONTROL · PERSONAL</p><h2>Hola, Marco 👋</h2><p>Tu información importante, en un solo lugar.</p></div><button class="home-action" id="mc-logout-action">Cerrar sesión</button></div>
      <div class="card home-kpi home-pink"><div class="home-icon">💳</div><div class="home-label">Gasto del mes</div><div class="home-value" id="mc-home-expense">$0.00</div></div>
      <div class="card home-kpi home-mint"><div class="home-icon">🎯</div><div class="home-label">Metas activas</div><div class="home-value" id="mc-home-goals">0</div></div>
      <div class="card home-kpi home-sky"><div class="home-icon">👟</div><div class="home-label">Pasos hoy</div><div class="home-value" id="mc-home-steps">Sin registrar</div></div>
      <div class="card home-kpi home-peach"><div class="home-icon">✓</div><div class="home-label">Hábitos de hoy</div><div class="home-value" id="mc-home-habits">Sin registrar</div></div>
      <div class="card home-panel home-panel-wide"><h3>Qué hacer ahora</h3><div class="home-list" id="mc-home-actions"><div class="home-empty">No hay acciones pendientes todavía.</div></div></div>
      <div class="card home-panel home-panel-side"><h3>Resumen</h3><div class="home-empty" id="mc-home-summary">Aún no hay datos suficientes para mostrar un resumen.</div></div>
      <div class="home-modules">
        <button class="card home-module home-module-pink" data-view="registrar"><div><h4>Finanzas</h4><p>Controla ingresos y gastos.</p></div><span class="module-icon">$</span></button>
        <button class="card home-module home-module-mint" data-view="metas"><div><h4>Metas</h4><p>Visualiza y actualiza tu progreso.</p></div><span class="module-icon">◎</span></button>
        <button class="card home-module home-module-sky" data-view="bienestar"><div><h4>Bienestar</h4><p>Salud, energía y equilibrio.</p></div><span class="module-icon">♡</span></button>
        <button class="card home-module home-module-peach" data-view="alimentacion"><div><h4>Alimentación</h4><p>Registra tus comidas.</p></div><span class="module-icon">◌</span></button>
        <button class="card home-module home-module-sky" data-view="ejercicio"><div><h4>Ejercicio</h4><p>Planes y sesiones.</p></div><span class="module-icon">✦</span></button>
        <button class="card home-module home-module-mint" data-view="habitos"><div><h4>Hábitos</h4><p>Construye constancia.</p></div><span class="module-icon">✓</span></button>
      </div>`;
    dash.appendChild(home);
    document.getElementById('mc-logout-action')?.addEventListener('click',()=>document.getElementById('logoutButton')?.click());
    home.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
  }
  function syncHome(){
    const expense=document.getElementById('monthExpense');if(expense){const t=document.getElementById('mc-home-expense');if(t)t.textContent=expense.textContent||'$0.00'}
    const goals=document.querySelectorAll('.goal-card').length;const g=document.getElementById('mc-home-goals');if(g)g.textContent=String(goals);
    const steps=document.querySelector('[id*=steps]');const st=document.getElementById('mc-home-steps');if(st&&steps&&steps.textContent.trim())st.textContent=steps.textContent.trim();
  }
  function navigate(view){document.querySelectorAll('.mc-safe-nav button,.mc-safe-bottom button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('[data-view="'+view+'"]').forEach(b=>b.classList.add('active'));try{if(typeof window.show==='function')window.show(view,document.querySelector('#tabs button'))}catch(e){console.warn('Navigation bridge:',e)}}
  function install(){
    addStyle();document.documentElement.classList.add('phase1');document.body.classList.add('mc-page');
    const sidebar=document.createElement('aside');sidebar.className='mc-safe-sidebar';sidebar.setAttribute('aria-label','Navegación principal');sidebar.innerHTML='<div class="mc-safe-brand"><span class="mc-safe-mark">M</span><div><strong>Mi Centro de Control</strong><small>Personal</small></div></div><nav class="mc-safe-nav"><button data-view="dashboard" class="active">⌂ &nbsp; Inicio</button><button data-view="registrar">$ &nbsp; Finanzas</button><button data-view="finanzas">▤ &nbsp; Presupuestos</button><button data-view="metas">◎ &nbsp; Metas</button><button data-view="bienestar">♡ &nbsp; Bienestar</button><button data-view="alimentacion">◌ &nbsp; Alimentación</button><button data-view="ejercicio">✦ &nbsp; Ejercicio</button><button data-view="pasos">👟 &nbsp; Pasos</button><button data-view="habitos">✓ &nbsp; Hábitos</button><button data-view="estado-emocional">☺ &nbsp; Estado emocional</button><button data-view="estudio">⌂ &nbsp; Demeter Studio</button></nav><div class="mc-safe-foot"><span>MXN</span><span>America/Mexico_City</span></div></aside>';
    const bottom=document.createElement('nav');bottom.className='mc-safe-bottom';bottom.setAttribute('aria-label','Navegación móvil');bottom.innerHTML='<button data-view="dashboard" class="active"><span>⌂</span>Inicio</button><button data-view="registrar"><span>$</span>Finanzas</button><button data-view="metas"><span>◎</span>Metas</button><button data-view="bienestar"><span>♡</span>Bienestar</button>';
    document.body.prepend(sidebar);document.body.appendChild(bottom);
    sidebar.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));bottom.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
    buildHome();syncHome();setInterval(syncHome,1200);
    const p6css=document.createElement('link');p6css.rel='stylesheet';p6css.href='phase6-wellbeing.css';document.head.appendChild(p6css);
    const p6script=document.createElement('script');p6script.src='phase6-wellbeing.js';p6script.defer=true;document.body.appendChild(p6script);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();