(()=>{
'use strict';
const $=id=>document.getElementById(id);
const money=v=>'$'+Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const labels={pending:'Pendiente',active:'Activa',paused:'Pausada',completed:'Completada',cancelled:'Cancelada'};
const categories=['Finanzas personales','Finanzas del estudio','Salud','Alimentación','Ejercicio','Pasos','Hábitos','Proyectos','Crecimiento del estudio'];
let goals=[]; let initialized=false; let milestones={};
function calc(g){const target=Number(g.target_value||0),current=Number(g.current_value||0);const pct=target>0?Math.min(100,Math.max(0,current/target*100)):0;const due=g.deadline?new Date(g.deadline+'T23:59:59'):null;const days=due&&!Number.isNaN(due.getTime())?Math.ceil((due-new Date())/86400000):null;const late=days!==null&&days<0&&g.status!=='completed'&&g.status!=='cancelled';return{target,current,pct,days,late};}
function inject(){const host=$('goalsPage');if(!host||$('customGoalsMount'))return;if(!initialized){initialized=true;const css=document.createElement('style');css.textContent='.custom-goals{margin-top:14px;padding-top:14px;border-top:1px solid #292d32}.custom-title{display:flex;justify-content:space-between;align-items:center;gap:10px}.custom-add{border:1px solid #ff2f79;background:#351622;color:#ff78aa;border-radius:12px;padding:9px 12px;font-weight:850}.custom-card{background:#15181c;border:1px solid #2b3035;border-radius:17px;padding:14px;margin-top:9px}.custom-actions{display:flex;gap:7px;margin-top:10px}.custom-actions button{flex:1}.custom-empty{color:#92979b;font-size:12px;padding:10px 0}.goal-modal{position:fixed;inset:0;background:rgba(0,0,0,.78);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;z-index:40;padding:12px}.goal-modal-card{width:min(560px,100%);max-height:90vh;overflow:auto;background:#16191c;border:1px solid #2b3035;border-radius:24px;padding:20px}.goal-modal-head{display:flex;justify-content:space-between;align-items:center}.goal-modal-head h2{margin:0}.goal-close{border:0;background:#25292d;color:#fff;border-radius:50%;width:34px;height:34px;font-size:18px}.goal-modal form{display:grid;gap:9px;margin-top:12px}.goal-modal label{font-size:12px;color:#92979b;font-weight:750}.goal-modal input,.goal-modal select,.goal-modal textarea{width:100%;box-sizing:border-box;border:1px solid #30353a;border-radius:14px;padding:12px;background:#1a1d21;color:#f7f7f5}.goal-modal textarea{min-height:70px;resize:vertical}.goal-grid2{display:grid;grid-template-columns:1fr 1fr;gap:9px}.goal-modal .primary{border:0;background:linear-gradient(135deg,#ff2f79,#ff4d8d);color:#fff;border-radius:14px;padding:13px;font-weight:900}.goal-milestones{margin-top:11px;padding-top:10px;border-top:1px solid #292d32}.goal-milestone{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid #292d32;font-size:12px}.goal-milestone:last-child{border-bottom:0}.goal-milestone button{border:0;background:transparent;color:#8cde7a}.goal-error{color:#ffd9de;background:#2a161b;border:1px solid #51242d;border-radius:12px;padding:10px;font-size:12px}@media(min-width:720px){.goal-modal{align-items:center}.goal-modal-card{border-radius:24px}}';document.head.appendChild(css);
const modal=document.createElement('div');modal.id='customGoalModal';modal.className='goal-modal hidden';modal.innerHTML='<div class="goal-modal-card"><div class="goal-modal-head"><h2 id="customGoalHeading">Nueva meta</h2><button type="button" class="goal-close" id="customGoalClose">×</button></div><div id="customGoalError" class="goal-error hidden"></div><form id="customGoalForm"><input id="customGoalId" type="hidden"><label>Nombre<input id="customGoalName" maxlength="120" required></label><div class="goal-grid2"><label>Categoría<select id="customGoalCategory">'+categories.map(x=>`<option>${x}</option>`).join('')+'</select></label><label>Estado<select id="customGoalStatus"><option value="pending">Pendiente</option><option value="active">Activa</option><option value="paused">Pausada</option><option value="completed">Completada</option><option value="cancelled">Cancelada</option></select></label></div><label>Descripción<textarea id="customGoalDescription"></textarea></label><label>Motivo<textarea id="customGoalReason"></textarea></label><div class="goal-grid2"><label>Fecha de inicio<input id="customGoalStart" type="date"></label><label>Fecha límite<input id="customGoalDate" type="date"></label></div><div class="goal-grid2"><label>Objetivo<input id="customGoalTarget" type="number" min="0" step=".01"></label><label>Progreso actual<input id="customGoalCurrent" type="number" min="0" step=".01" value="0"></label></div><div class="goal-grid2"><label>Unidad<input id="customGoalUnit" placeholder="MXN, kg, pasos..."></label><label>Notas<input id="customGoalNotes"></label></div><div id="milestoneSection" class="goal-milestones hidden"><b>Hitos</b><div id="milestoneList"></div><button type="button" class="secondary" id="addMilestone" style="margin-top:8px">＋ Añadir hito</button></div><button type="submit" class="primary">Guardar meta</button></form></div></div>';document.body.appendChild(modal);$('customGoalClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};$('customGoalForm').onsubmit=saveGoal;$('addMilestone').onclick=addMilestone;}
const wrap=document.createElement('div');wrap.id='customGoalsMount';wrap.className='custom-goals';wrap.innerHTML='<div class="custom-title"><div><div class="kicker">🎯 Metas</div><div class="note">Metas reales guardadas en Supabase, protegidas por tu sesión.</div></div><button type="button" class="custom-add" id="addCustomGoal">＋ Nueva meta</button></div><div id="customGoalList"></div>';host.appendChild(wrap);$('addCustomGoal').onclick=()=>open();render();load();}
async function load(){if(typeof supabaseClient==='undefined'||!supabaseClient)return;if(typeof currentUser==='undefined'||!currentUser)return;const {data,error}=await supabaseClient.from('goals').select('*').order('deadline',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(error){showError(error.message);return}goals=data||[];await loadMilestones();render();}
async function loadMilestones(){milestones={};if(!goals.length)return;const ids=goals.map(g=>g.id);const {data,error}=await supabaseClient.from('goal_milestones').select('*').in('goal_id',ids).order('sort_order').order('created_at');if(error){showError(error.message);return}(data||[]).forEach(m=>(milestones[m.goal_id]??=[]).push(m));}
function showError(m){const e=$('customGoalError');if(e){e.textContent=m;e.classList.remove('hidden')}}
function clearError(){const e=$('customGoalError');if(e)e.classList.add('hidden')}
function open(id){clearError();const g=goals.find(x=>x.id===id);$('customGoalHeading').textContent=g?'Editar meta':'Nueva meta';$('customGoalId').value=g?.id||'';$('customGoalName').value=g?.name||'';$('customGoalCategory').value=g?.category||'Proyectos';$('customGoalStatus').value=g?.status||'pending';$('customGoalDescription').value=g?.description||'';$('customGoalReason').value=g?.reason||'';$('customGoalStart').value=g?.start_date||'';$('customGoalDate').value=g?.deadline||'';$('customGoalTarget').value=g?.target_value??'';$('customGoalCurrent').value=g?.current_value??0;$('customGoalUnit').value=g?.unit||'';$('customGoalNotes').value=g?.notes||'';$('milestoneSection').classList.toggle('hidden',!g);renderMilestones(g?.id);$('customGoalModal').classList.remove('hidden');setTimeout(()=>$('customGoalName').focus(),0)}
function close(){$('customGoalModal').classList.add('hidden')}
async function saveGoal(e){e.preventDefault();clearError();const target=$('customGoalTarget').value===''?null:Number($('customGoalTarget').value),current=Number($('customGoalCurrent').value||0);if(target!==null&&(target<0||current>target))return showError('El progreso no puede superar el objetivo.');const payload={name:$('customGoalName').value.trim(),category:$('customGoalCategory').value,status:$('customGoalStatus').value,description:$('customGoalDescription').value.trim()||null,reason:$('customGoalReason').value.trim()||null,start_date:$('customGoalStart').value||null,deadline:$('customGoalDate').value||null,target_value:target,current_value:current,unit:$('customGoalUnit').value.trim()||null,notes:$('customGoalNotes').value.trim()||null};if(!payload.name)return showError('Escribe un nombre para la meta.');if(target!==null&&current>=target&&current>0)payload.status='completed';const id=$('customGoalId').value;const q=id?supabaseClient.from('goals').update(payload).eq('id',id):supabaseClient.from('goals').insert(payload).select('id').single();const {data,error}=await q;if(error)return showError(error.message);if(!id)$('milestoneSection').classList.remove('hidden');close();await load();}
async function addMilestone(){const id=$('customGoalId').value;if(!id)return;const name=prompt('Nombre del hito:');if(!name?.trim())return;const target=prompt('Valor del hito (opcional):','');const next=(milestones[id]||[]).length;const {error}=await supabaseClient.from('goal_milestones').insert({goal_id:id,name:name.trim(),target_value:target===''?null:Number(target),sort_order:next});if(error)showError(error.message);else await load();open(id)}
function renderMilestones(id){const list=$('milestoneList');if(!list)return;const ms=id?(milestones[id]||[]):[];list.innerHTML=ms.length?ms.map(m=>`<div class="goal-milestone"><span>${esc(m.name)}${m.target_value!==null?' · '+money(m.target_value):''}</span><button type="button" onclick="window.completeMilestone('${m.id}')">${m.completed_at?'✓ Completado':'Marcar'}</button></div>`).join(''):'<div class="note" style="margin-top:8px">No hay hitos todavía.</div>'}
window.completeMilestone=async id=>{const m=(Object.values(milestones).flat()).find(x=>x.id===id);if(!m)return;const {error}=await supabaseClient.from('goal_milestones').update({completed_at:m.completed_at?null:new Date().toISOString()}).eq('id',id);if(error)showError(error.message);else{await load();open(m.goal_id)}};
window.editCustomGoal=id=>open(id);
window.deleteCustomGoal=async id=>{if(!confirm('¿Eliminar esta meta? Esta acción no se puede deshacer.'))return;const {error}=await supabaseClient.from('goals').delete().eq('id',id);if(error)alert(error.message);else load()};
window.advanceCustomGoal=async id=>{const g=goals.find(x=>x.id===id);if(!g)return;const v=prompt('Nuevo progreso actual:',g.current_value??0);if(v===null)return;const n=Number(v);if(!Number.isFinite(n)||n<0)return alert('Introduce un número válido.');if(g.target_value!==null&&n>Number(g.target_value))return alert('El progreso no puede superar el objetivo.');const status=g.target_value!==null&&n>=Number(g.target_value)?'completed':g.status==='completed'?'active':g.status;const {error}=await supabaseClient.from('goals').update({current_value:n,status}).eq('id',id);if(error)alert(error.message);else load()};
function render(){const e=$('customGoalList');if(!e)return;if(!goals.length){e.innerHTML='<div class="custom-empty">Todavía no tienes metas registradas.</div>';return}e.innerHTML=goals.map(g=>{const c=calc(g),status=labels[g.status]||g.status,badge=g.status==='completed'?'low':c.late?'high':'';return `<div class="custom-card"><div class="goal-top"><div><div class="goal-title">${esc(g.name)}</div><div class="muted">${esc(g.category)}</div></div><div class="goal-priority ${badge}">${status}</div></div><div class="goal-value">${money(c.current)}${g.unit?' '+esc(g.unit):''}</div><div class="muted">${c.target?`Objetivo: ${money(c.target)}${g.unit?' '+esc(g.unit):''}`:'Meta cualitativa'}${g.deadline?' · '+esc(g.deadline):''}</div><div class="progress" style="margin-top:10px"><div class="fill ${g.category==='Salud'||g.category==='Hábitos'?'green':''}" style="width:${c.pct}%"></div></div><div class="goal-grid" style="margin-top:10px"><div class="goal-kpi"><span>Progreso</span><b>${c.pct.toFixed(1)}%</b></div><div class="goal-kpi"><span>${c.days===null?'Plazo':'Días restantes'}</span><b>${c.days===null?'Sin fecha':c.days<0?'Vencida':c.days}</b></div></div><div class="goal-next"><b>Motivo:</b> ${esc(g.reason||'Sin motivo registrado')} ${g.description?'<br><span>'+esc(g.description)+'</span>':''}</div><div class="custom-actions"><button type="button" class="secondary" onclick="editCustomGoal('${g.id}')">Editar</button><button type="button" class="secondary" onclick="advanceCustomGoal('${g.id}')">Actualizar progreso</button><button type="button" class="icon-btn delete" onclick="deleteCustomGoal('${g.id}')">Eliminar</button></div>${(milestones[g.id]||[]).length?'<div class="note" style="margin-top:9px">Hitos: '+(milestones[g.id]||[]).filter(m=>m.completed_at).length+'/'+milestones[g.id].length+' completados</div>':''}</div>`}).join('');}
function watch(){const host=$('goalsPage');if(!host)return;new MutationObserver(()=>{if(!$('customGoalsMount'))inject()}).observe(host,{childList:true});inject();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();