from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')

old_section = re.search(r'<section id="registrar" class="view">.*?</section>\n<section id="finanzas"', s, re.S)
if not old_section:
    raise SystemExit('No se encontró la sección registrar')

new_section = '''<section id="registrar" class="view"><div class="quick"><button onclick="setMovementType('expense')">− Gasto</button><button onclick="setMovementType('income')">＋ Ingreso</button><button onclick="setMovementType('transfer')">↔ Transferencia</button></div><div class="card"><div class="kicker">➕ Registro rápido</div><h2>Nuevo movimiento</h2><div class="note">Área activa: <b id="formAreaLabel">Personal</b></div><form id="form"><label>Tipo<select id="type" onchange="toggleMovementFields()"><option value="expense">Gasto / egreso</option><option value="income">Ingreso</option><option value="transfer">Transferencia</option></select></label><label>Monto<input id="amount" type="number" min="0" step=".01" placeholder="0.00" required></label><div id="normalMovementFields"><label>Cuenta<select id="account" required></select></label><label>Concepto<input id="concept" placeholder="Ej. Supermercado"></label></div><div id="transferFields" class="hidden"><label>Cuenta origen<select id="transferFrom"></select></label><label>Cuenta destino<select id="transferTo"></select></label><label>Concepto<input id="transferConcept" placeholder="Ej. Pasar a ahorro"></label></div><label>Fecha<input id="transactionDate" type="date" required></label><button id="saveButton" class="primary">Guardar movimiento</button></form></div><div class="card" style="margin-top:11px"><div class="kicker">🧾 Historial · <span id="historyAreaLabel">Personal</span></div><div class="note" style="margin:5px 0">Edita o elimina directamente desde aquí.</div><div id="history"></div></div></section>
<section id="finanzas"'''
s = s[:old_section.start()] + new_section + s[old_section.end()-len('<section id="finanzas"'):]

pattern = re.compile(r"\$\('form'\)\.addEventListener\('submit',async e=>\{.*?\}\);\n\$\('transferForm'\)\.addEventListener\('submit',async e=>\{.*?\}\);", re.S)
replacement = r'''function setMovementType(type){$('type').value=type;toggleMovementFields();if(type==='transfer')$('transferFrom').focus();else $('amount').focus()}function toggleMovementFields(){const transfer=$('type').value==='transfer';$('normalMovementFields').classList.toggle('hidden',transfer);$('transferFields').classList.toggle('hidden',!transfer);$('account').required=!transfer;$('transferFrom').required=transfer;$('transferTo').required=transfer} $('form').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return error('Sesión requerida','Inicia sesión antes de registrar movimientos.');const amount=Number($('amount').value),type=$('type').value,date=$('transactionDate').value,b=$('saveButton');if(amount<=0)return toast('Revisa el monto.');b.disabled=true;b.textContent=type==='transfer'?'Transfiriendo...':'Guardando...';try{if(type==='transfer'){const fromId=$('transferFrom').value,toId=$('transferTo').value,concept=$('transferConcept').value.trim()||'Transferencia',from=accountsData.find(a=>a.id===fromId),to=accountsData.find(a=>a.id===toId);if(!from||!to)return toast('Selecciona origen y destino.');if(fromId===toId)return toast('Origen y destino deben ser diferentes.');if(Number(from.balance||0)<amount)return toast('La cuenta origen no tiene suficiente saldo.');const base=TRANSFER+concept;let r=await supabaseClient.from('transactions').insert([{amount,type:'expense',account_id:fromId,concept:base+' → '+to.name,transaction_date:date,user_id:currentUser.id,area:currentArea},{amount,type:'income',account_id:toId,concept:base+' ← '+from.name,transaction_date:date,user_id:currentUser.id,area:currentArea}]);if(r.error)throw r.error;await adjustAccount(fromId,-amount);await adjustAccount(toId,amount);toast('Transferencia realizada.')}else{const accountId=$('account').value,concept=$('concept').value.trim(),account=accountsData.find(a=>a.id===accountId);if(!account)return toast('Selecciona una cuenta.');if(type==='expense'&&Number(account.balance)<amount)return toast('La cuenta no tiene suficiente saldo.');let r=await supabaseClient.from('transactions').insert({amount,type,account_id:accountId,concept:concept||(type==='income'?'Ingreso':'Gasto'),transaction_date:date,user_id:currentUser.id,area:currentArea});if(r.error)throw r.error;await adjustAccount(accountId,type==='income'?amount:-amount);toast('Movimiento guardado.')} $('form').reset();$('type').value='expense';toggleMovementFields();setToday();await load()}catch(x){error('No se pudo guardar el movimiento',x.message)}finally{b.disabled=false;b.textContent='Guardar movimiento'}});'''
if not pattern.search(s):
    raise SystemExit('No se encontraron los manejadores de movimiento')
s = pattern.sub(replacement, s, count=1)
p.write_text(s, encoding='utf-8')
print('ok')
